theme: jekyll-theme-cayman
title: My website!
description: This is MY website and is for ME only! Ok well a few exceptions. also mom tell me how good the website is. love you mom! ok well back to the topic, this is my first ever website, and I even made it all by myself. all it took was learning how to use github's website maker which requires little to no coding at all! (well you do have to edit the scripts and what not but whatever)
